### ISSUE TITLE
Fuente incompleta

### ISSUE THREAD

**Issue by erickorlando** [codercampos/XF-localnotifications#1]
Sería de gran ayuda que puedas subir la fuente completa de tu articulo https://xamarinlatino.com/local-notifications-en-xamarin-forms-4d213092d0c ya que me habia hecho ilusiones de encontrarlo, gracias.

**Comment by codercampos** [comment]
@erickorlando 
Te agradezco mucho la observación. Realmente no me había dado cuenta de que no subí el proyecto completo. Ahora debe estar disponible. Gracias.
